# Generated by Django 2.0.3 on 2018-07-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Enter a brief description of the wine', max_length=1000)),
                ('designation', models.CharField(max_length=200)),
                ('points', models.IntegerField(default=0)),
                ('price', models.FloatField(blank=True, null=True)),
                ('province', models.CharField(max_length=200)),
                ('region_1', models.CharField(max_length=200)),
                ('region_2', models.CharField(max_length=200)),
                ('variety', models.CharField(max_length=200)),
                ('winery', models.CharField(max_length=200)),
            ],
        ),
    ]
